# image will be published to ghcr.io/<user>/<name>
name: gunzy-os
# description will be included in the image's metadata
description: An opinionated build of uBlue for personal use by @gunzy83.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/gunzy83/gunzy-os/repo/fedora-%OS_VERSION%/gunzy83-gunzy-os-fedora-%OS_VERSION%.repo
    install:
      - applet-betterinlineclock
      - applet-window-appmenu
      - applet-window-title
      - bind-utils
      - cherry-kde-theme
      - crudini
      - git
      - gparted
      - kvantum
      - libappindicator
      - numix-icon-theme-circle
      - pam-u2f
      - pamu2fcfg
      - solaar
      - starship
      - tailscale
      - vim
      - yakuake
      - zsh
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - 1password # install 1Password (stable) and `op` CLI tool
      - ublue-os-wallpapers
      - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section

  - type: script
    scripts:
      - install-wavebox.sh
      - install-chezmoi.sh
      - setup-pam-u2f.sh
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
